Repository kazuki1023/miniHackathon-202312, pull requests merged in 2023-12, with the labels that each got.

#31 laravelの日本語対応
  src/composer.json
  src/composer.lock
  src/config/app.php
  src/lang/ja.json
  src/lang/ja/auth.php
  src/lang/ja/pagination.php
  src/lang/ja/passwords.php
  src/lang/ja/validation.php
Labels: ReviewWanted

#32 ✨ テーブル作成した
  src/database/migrations/2023_12_09_030220_create_contents_table.php
  src/database/migrations/2023_12_09_030832_create_details_table.php
  src/database/migrations/2023_12_09_031022_create_faculties_table.php
  src/database/migrations/2023_12_09_031448_create_club_table.php
  src/database/migrations/2023_12_09_031558_create_images_table.php
  src/database/migrations/2023_12_09_031812_add_role_to_users_table.php
Labels: S

#35 ダミーデータ作成
  src/database/factories/UserFactory.php
  src/database/seeders/ClubSeeder.php
  src/database/seeders/ContentsSeeder.php
  src/database/seeders/DatabaseSeeder.php
  src/database/seeders/UsersSeeder.php
Labels: S, ReviewWanted

#37 新規登録時に登録メールの送信
  src/app/Models/User.php
Labels: ReviewWanted

#39 ✨ usersテーブルにclub_idが抜けていたので追加
  src/database/migrations/2023_12_09_054834_add_club_id_to_users_table.php
  src/database/seeders/DatabaseSeeder.php
  src/database/seeders/UsersSeeder.php
  src/resources/views/layouts/sidebar.blade.php
Labels: S, ReviewWanted

#40 管理者一覧ページ(roleによって表示変更)
  src/app/Http/Controllers/ClubController.php
  src/app/Http/Controllers/UserController.php
  src/app/Models/Club.php
  src/app/Models/User.php
  src/app/Services/UserService.php
  src/resources/views/dashboard.blade.php
  src/routes/web.php
Labels: M, ReviewWanted
